spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flowforge
      auto-index-creation: true

server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-enough-for-hs256}
  expiration: 86400000 # 24 hours in milliseconds
  refresh:
    expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    com.github.tanyonghe.flowforge: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO 