spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flowforge
      auto-index-creation: true

  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret-key-here}
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.github.tanyonghe.flowforge: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO 